from .AbstractReducer import AbstractReducer
from .DummyReducer import DummyReducer
from .PCA import PCA
from .UMAP import UMAP
from .NCVis import NCVis
from .Isomap import Isomap
from .LLE import LLE
from .MDS import MDS
# from .DiffusionMap import DiffusionMap
from .FA import FA
from .Chalmer import Chalmer
from .SpringForce import SpringForce
from .ForceHybrid import ForceHybrid
from .ForcePivot import ForcePivot
from .GTM import GTM
from .FastICA import FastICA
from .LaplacianEigenmaps import LaplacianEigenmaps
from .H_LLE import H_LLE
from .M_LLE import M_LLE
from .LTSA_LLE import LTSA_LLE
from .LPP import LPP
from .N_MDS import N_MDS
from .NMF import NMF
from .IPCA import IPCA
from .K_PCA_P import K_PCA_P
from .K_PCA_R import K_PCA_R
from .K_PCA_S import K_PCA_S
from .SparsePCA import SparsePCA
from .GRP import GRP
from .SRP import SRP
from .TSNE import TSNE
from .TSVD import TSVD
